assets: /hpc2hdd/home/kluo573/EVO_1/Evo-1/LIBERO_evaluation/LIBERO/libero/libero/./assets
bddl_files: /hpc2hdd/home/kluo573/EVO_1/Evo-1/LIBERO_evaluation/LIBERO/libero/libero/./bddl_files
benchmark_root: /hpc2hdd/home/kluo573/EVO_1/Evo-1/LIBERO_evaluation/LIBERO/libero/libero
datasets: /hpc2hdd/home/kluo573/EVO_1/Evo-1/LIBERO_evaluation/LIBERO/libero/datasets
init_states: /hpc2hdd/home/kluo573/EVO_1/Evo-1/LIBERO_evaluation/LIBERO/libero/libero/./init_files
